on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Test & Release"
jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      PATH: $ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Or any specific version of Flutter

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install Android SDK
        run: |
          sudo mkdir -p /usr/local/android-sdk
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android_tools.zip
          unzip android_tools.zip -d /usr/local/android-sdk/cmdline-tools
          mv /usr/local/android-sdk/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator"

      - name: Install Android Emulator
        run: sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"

      - name: Start emulator
        run: |
          nohup emulator -avd test -no-audio -no-window -no-snapshot &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          flutter devices

      - name: Run integration tests on Android
        run: flutter test integration_test -d emulator-5554

      - name: Stop emulator
        run: adb emu kill

      - run: flutter build apk --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CICD_TOKEN }}






# push to master, main, develop
# pull request on main master